; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_rondo_of_blood_lmao=music_data_rondo_of_blood_lmao
.endif

music_data_rondo_of_blood_lmao:
	.byte 1
	.word @instruments
	.word @samples-5
; 00 : New song
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 286,238

.export music_data_rondo_of_blood_lmao
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env6,@env4,@env20,@env0 ; 00 : hat
	.word @env8,@env22,@env20,@env0 ; 01 : kick
	.word @env13,@env18,@env1,@env0 ; 02 : snare
	.word @env7,@env4,@env20,@env0 ; 03 : rel hats
	.word @env17,@env16,@env1,@env0 ; 04 : funny distort guitar
	.word @env10,@env16,@env20,@env0 ; 05 : funny fadein
	.word @env17,@env16,@env20,@env0 ; 06 : blank / DMC
	.word @env17,@env15,@env20,@env0 ; 07 : chords
	.word @env9,@env15,@env20,@env0 ; 08 : blank arp (0x)
	.word @env2,@env16,@env20,@env12 ; 09 : triangle drums
	.word @env9,@env14,@env20,@env0 ; 0a : blank arp (0xy)

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c1,$c0,$00,$01
@env2:
	.byte $00,$c9,$c8,$c7,$c6,$c6,$c5,$c5,$c4,$00,$08
@env3:
	.byte $c0,$c0,$c4,$c4,$00,$00
@env4:
	.byte $bd,$c0,$00,$01
@env5:
	.byte $c0,$c0,$c7,$c7,$00,$00
@env6:
	.byte $00,$c8,$c4,$c2,$c0,$00,$04
@env7:
	.byte $00,$cc,$ca,$c8,$c7,$c6,$c5,$c5,$c4,$c3,$c3,$c2,$02,$c1,$00,$0d
@env8:
	.byte $00,$cd,$c9,$c5,$c2,$c1,$c0,$00,$06
@env9:
	.byte $00,$cf,$7f,$00,$02
@env10:
	.byte $07,$c1,$c2,$c4,$c8,$00,$04,$c4,$c2,$c1,$c0,$00,$0a
@env11:
	.byte $c0,$c0,$c8,$c8,$00,$00
@env12:
	.byte $80,$bf,$f1,$00,$02
@env13:
	.byte $00,$cd,$cb,$c8,$c6,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$0b
@env14:
	.byte $80,$80,$ff,$ff,$c0,$c0,$00,$00
@env15:
	.byte $ff,$ff,$c0,$c0,$00,$00
@env16:
	.byte $c0,$7f,$00,$01
@env17:
	.byte $04,$cf,$00,$01,$cc,$c9,$c7,$00,$06
@env18:
	.byte $c6,$cc,$00,$01
@env19:
	.byte $c0,$c0,$c5,$c5,$00,$00
@env20:
	.byte $7f,$00,$00
@env21:
	.byte $c0,$c0,$c3,$c3,$00,$00
@env22:
	.byte $c9,$cf,$00,$01
@env23:
	.byte $c0,$c0,$c2,$c2,$c5,$c5,$00,$00
@env24:
	.byte $00,$c0,$bf,$be,$02,$bf,$c0,$c0,$c1,$c2,$02,$c1,$00,$01

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$d4,$0f,$40,$00 ; 00 A# (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$c8,$0d,$40,$01 ; 01 B (Pitch:13)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$bc,$07,$40,$00 ; 02 C (Pitch:7)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$bc,$09,$40,$00 ; 03 C (Pitch:9)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$bc,$0a,$40,$00 ; 04 C (Pitch:10)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$bc,$0c,$40,$00 ; 05 C (Pitch:12)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$bc,$0e,$40,$00 ; 06 C (Pitch:14)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$bc,$0f,$40,$00 ; 07 C (Pitch:15)
	.byte $33+.lobyte(FAMISTUDIO_DPCM_PTR),$b0,$08,$40,$01 ; 08 C# (Pitch:8)
	.byte $33+.lobyte(FAMISTUDIO_DPCM_PTR),$b0,$09,$40,$01 ; 09 C# (Pitch:9)
	.byte $33+.lobyte(FAMISTUDIO_DPCM_PTR),$b0,$0a,$40,$01 ; 0a C# (Pitch:10)
	.byte $33+.lobyte(FAMISTUDIO_DPCM_PTR),$b0,$0b,$40,$01 ; 0b C# (Pitch:11)
	.byte $33+.lobyte(FAMISTUDIO_DPCM_PTR),$b0,$0d,$40,$01 ; 0c C# (Pitch:13)
	.byte $33+.lobyte(FAMISTUDIO_DPCM_PTR),$b0,$0e,$40,$01 ; 0d C# (Pitch:14)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$a8,$07,$40,$02 ; 0e D (Pitch:7)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$a8,$0a,$40,$02 ; 0f D (Pitch:10)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$a8,$0b,$40,$02 ; 10 D (Pitch:11)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$a8,$0c,$40,$02 ; 11 D (Pitch:12)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$a8,$0d,$40,$02 ; 12 D (Pitch:13)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$a8,$0e,$40,$02 ; 13 D (Pitch:14)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$a8,$0f,$40,$02 ; 14 D (Pitch:15)
	.byte $73+.lobyte(FAMISTUDIO_DPCM_PTR),$2b,$0e,$40,$00 ; 15 fdkick (Pitch:14)
	.byte $66+.lobyte(FAMISTUDIO_DPCM_PTR),$30,$0f,$40,$00 ; 16 Gimmick snare.dmc (Pitch:15)

@song0ch0:
	.byte $46, $01, $79, $4f, $00, $88
@song0ref7:
	.byte $17, $83, $19, $89, $00, $83, $19, $00, $87, $19, $00, $87, $17, $83, $19, $89, $00, $83
@song0ref25:
	.byte $19
@song0ref26:
	.byte $00, $87, $14, $83, $00, $83
@song0ref32:
	.byte $17, $83, $19, $89, $00, $83, $19, $00, $87, $19, $00, $87, $19, $83, $00, $83, $19, $00, $87, $19, $00, $87, $17, $83
	.byte $00, $83, $17, $83, $19, $89, $00, $83, $19, $00, $87, $19, $00, $87
@song0ref70:
	.byte $1c, $87, $00, $19, $00, $87, $19, $00, $87
@song0ref79:
	.byte $19, $83, $1b, $89, $00, $83, $17, $83, $00, $83, $17, $00, $87, $17, $83, $19, $89, $00, $83, $14, $00, $87, $12, $00
	.byte $87, $14, $00, $87
	.byte $41, $32
	.word @song0ref7
	.byte $e3, $12, $89, $06, $95, $08, $95, $0b, $95, $0c, $87, $4f, $02, $81
@song0ch0loop:
	.byte $7a
@song0ref126:
	.byte $50, $f1, $2a, $2c, $87, $43, $20, $8b, $49, .lobyte(@env24), .hibyte(@env24), $97, $45, $ab, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $81, $88, $50, $f1, $2a, $2c, $87, $43, $20, $97, $1e, $a1, $23, $95, $50, $f1, $2a, $2c, $87, $43, $20, $8b, $49
	.byte .lobyte(@env24), .hibyte(@env24), $97, $45, $ab, $49, .lobyte(@env0), .hibyte(@env0), $4a, $81, $88, $50, $f1, $2a
	.byte $2c, $87, $43, $20, $97, $1e, $a1, $25, $95, $50, $f1, $2a, $2c, $87, $43, $20, $8b, $49, .lobyte(@env24), .hibyte(@env24)
	.byte $97, $45, $ab, $49, .lobyte(@env0), .hibyte(@env0), $4a, $81, $88, $50, $f1, $2a, $2c, $87, $43, $20, $97, $1e, $a1
	.byte $27, $95, $50, $f1, $2a, $2c, $87, $43, $20, $8b, $49, .lobyte(@env24), .hibyte(@env24), $97, $45, $ff, $8d, $88
	.byte $41, $36
	.word @song0ref126
@song0ref241:
	.byte $ad, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $2c, $a1, $2d, $a1, $2f, $95, $2c, $95, $79, $49, .lobyte(@env24)
	.byte .hibyte(@env24), $97, $78, $97, $77, $97, $76, $97, $75, $8b, $7a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $2a
	.byte $95, $49, .lobyte(@env24), .hibyte(@env24), $8b, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $25, $95, $2c, $95
	.byte $79, $49, .lobyte(@env24), .hibyte(@env24), $97, $78, $97, $77, $97, $76, $97, $75, $8b, $7a, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $88, $2a, $95, $49, .lobyte(@env24), .hibyte(@env24), $8b, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $28
	.byte $95, $27, $95, $79, $49, .lobyte(@env24), .hibyte(@env24), $97, $78, $97, $77, $97, $76, $97, $75, $8b, $7a, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $88, $23, $95, $49, .lobyte(@env24), .hibyte(@env24), $8b, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $88, $20, $95, $49, .lobyte(@env0), .hibyte(@env0), $4a, $25, $95, $79, $49, .lobyte(@env24), .hibyte(@env24)
	.byte $97, $78, $97, $77, $97, $7a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $2c, $95, $49, .lobyte(@env24), .hibyte(@env24)
	.byte $8b, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $2d, $95, $49, .lobyte(@env24), .hibyte(@env24), $8b, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $88, $2f, $95, $2c, $95, $79, $49, .lobyte(@env24), .hibyte(@env24), $97, $78, $97, $77, $97, $7a
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $2c, $95, $49, .lobyte(@env24), .hibyte(@env24), $8b, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $88, $2d, $95, $49, .lobyte(@env24), .hibyte(@env24), $8b, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $88, $2f, $95, $2c, $95, $79, $49, .lobyte(@env24), .hibyte(@env24), $97, $78, $97, $77, $97, $7a, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $88, $2a, $95, $49, .lobyte(@env24), .hibyte(@env24), $8b, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $88, $25, $95, $49, .lobyte(@env24), .hibyte(@env24), $8b, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $2a
	.byte $95, $2c, $95, $79, $49, .lobyte(@env24), .hibyte(@env24), $97, $78, $97, $77, $97, $76, $af, $75, $af, $74, $af, $73
	.byte $af, $72, $af, $71, $af, $7a, $88
	.byte $41, $38
	.word @song0ref126
	.byte $88
	.byte $41, $36
	.word @song0ref126
	.byte $41, $5d
	.word @song0ref241
	.byte $7a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $25, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $79, $af
	.byte $78, $a3, $7a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $27, $95, $49, .lobyte(@env24), .hibyte(@env24), $8b
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $28, $95, $27, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $88, $25, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $88, $23, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $88, $25, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $23
	.byte $95, $49, .lobyte(@env24), .hibyte(@env24), $c7, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $20, $95, $23, $95
	.byte $49, .lobyte(@env24), .hibyte(@env24), $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $27, $95, $25, $95, $49
	.byte .lobyte(@env24), .hibyte(@env24), $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $26, $95, $49, .lobyte(@env24)
	.byte .hibyte(@env24), $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $25, $95, $49, .lobyte(@env24), .hibyte(@env24)
	.byte $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $23, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $88, $21, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $79, $af, $7a, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $88, $25, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $88, $28, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $27
	.byte $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $28, $95, $49, .lobyte(@env24)
	.byte .hibyte(@env24), $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $2a, $95, $49, .lobyte(@env24), .hibyte(@env24)
	.byte $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $25, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $88, $23, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $79, $af, $78, $af, $7a, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $88, $20, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $88, $24, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $79, $af, $7a, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $88, $24, $95, $49, .lobyte(@env24), .hibyte(@env24), $45, $89, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88
	.byte $25, $95, $49, .lobyte(@env24), .hibyte(@env24), $45, $89, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $27, $89
	.byte $45, $89, $49, .lobyte(@env0), .hibyte(@env0), $4a, $2f, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $79, $af
	.byte $7a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $2c, $95, $49, .lobyte(@env24), .hibyte(@env24), $91, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $85, $88, $50, $f3, $3d, $3f, $81, $43, $33, $91, $49, .lobyte(@env24), .hibyte(@env24), $97, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $88, $31, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $88, $2f, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $88, $2e, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $2c
	.byte $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $2b, $95, $49, .lobyte(@env24)
	.byte .hibyte(@env24), $97, $79, $af, $7a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $2c, $95, $49, .lobyte(@env24)
	.byte .hibyte(@env24), $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $2e, $95, $49, .lobyte(@env24), .hibyte(@env24)
	.byte $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $2f, $95, $79, $49, .lobyte(@env24), .hibyte(@env24), $97, $78
	.byte $97, $76, $97, $7c, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $2c, $95, $49, .lobyte(@env24), .hibyte(@env24)
	.byte $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $2e, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $7a, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $88, $2f, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $79, $af, $78, $af
	.byte $76, $97, $7a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $2e, $89, $2f, $89, $31, $95, $49, .lobyte(@env24), .hibyte(@env24)
	.byte $97, $79, $af, $78, $af, $76, $97, $7a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $2f, $89, $31, $89, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $33, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $79, $af, $78, $ff, $cb, $7a, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $88, $34, $89, $33, $89, $34, $89, $33, $89, $34, $89, $33, $89, $34, $89, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $33, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $79, $af, $78, $d9, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $45, $83, $4f, $01, $00, $dd, $79, $88, $12, $89, $06, $95, $08, $95, $0b, $95, $0c, $89, $42
	.word @song0ch0loop
@song0ch1:
	.byte $71, $4b, .lobyte(@env23), .hibyte(@env23), $94, $17, $c5, $72, $c7, $73, $c7, $74, $ff, $a7, $75, $ff, $ed, $4b, .lobyte(@env16)
	.byte .hibyte(@env16), $4c, $43, $17, $73, $4f, $02, $8c, $36
@song0ref1128:
	.byte $83, $33, $83, $31, $83, $2c, $83, $2a, $83, $25, $83, $1e, $83, $1b, $83, $19, $83, $14, $83, $0f, $89, $00, $c5
@song0ch1loop:
	.byte $4c
@song0ref1153:
	.byte $4f, $00, $45, $ad, $7a, $4b, .lobyte(@env11), .hibyte(@env11), $8e
@song0ref1162:
	.byte $14, $95, $45, $95, $4d, $14, $95, $45, $89, $4b, .lobyte(@env5), .hibyte(@env5), $14, $a1, $4b, .lobyte(@env11), .hibyte(@env11)
	.byte $14, $95, $45, $ad, $4d, $14, $95, $45, $95, $4d, $14, $95, $45, $89, $4b, .lobyte(@env5), .hibyte(@env5), $14, $a1
	.byte $4b, .lobyte(@env11), .hibyte(@env11), $14, $95, $4f, $00, $45, $ad, $4d, $14, $95, $45, $95, $4d, $14, $95, $45, $89
	.byte $4b, .lobyte(@env5), .hibyte(@env5), $14, $a1, $4b, .lobyte(@env11), .hibyte(@env11), $14, $95, $45, $ad, $4b, .lobyte(@env5)
	.byte .hibyte(@env5), $12, $95, $45, $95, $4d, $14, $a1, $4d, $14, $a1, $4d, $14, $95, $4f, $00, $45, $ad, $4b, .lobyte(@env11)
	.byte .hibyte(@env11)
	.byte $41, $34
	.word @song0ref1162
	.byte $7f, $4b, .lobyte(@env16), .hibyte(@env16), $4c, $8a, $19, $95, $49, .lobyte(@env24), .hibyte(@env24), $af, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $8a, $20, $85, $21, $85, $23, $85, $25, $95, $49, .lobyte(@env24), .hibyte(@env24), $c7, $79, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a
@song0ref1289:
	.byte $88, $17, $83, $19
@song0ref1293:
	.byte $89, $00, $83, $19, $00, $87, $19, $00, $87, $20, $83, $00, $83, $19, $00, $87, $19, $00, $87, $7f, $8a, $19, $89, $25
	.byte $95, $49, .lobyte(@env24), .hibyte(@env24), $8b, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a, $23, $95, $49, .lobyte(@env24)
	.byte .hibyte(@env24), $8b, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a, $1e, $95, $20, $95, $7d, $97, $7b, $97, $79, $97
	.byte $77, $97, $75, $8b, $7f, $1b, $a1, $17, $95, $79
	.byte $41, $16
	.word @song0ref1289
	.byte $41, $1c
	.word @song0ref79
	.byte $7f, $8a, $19, $c5, $14, $f5, $1b, $c5, $19, $c5, $1e, $ad, $20, $b9, $1e, $89, $19, $89, $16, $89, $14, $ad, $12, $ad
	.byte $79, $88, $19, $83, $1b
	.byte $41, $13
	.word @song0ref1293
	.byte $19, $83, $1b, $89, $00, $83, $14, $83, $00, $83, $14, $00, $87, $14, $83, $00, $83, $14, $00, $87, $14, $00, $87, $14
	.byte $00, $87, $14, $00, $87
	.byte $41, $38
	.word @song0ref1153
	.byte $4b, .lobyte(@env11), .hibyte(@env11)
	.byte $41, $34
	.word @song0ref1162
	.byte $00, $95, $71, $4b, .lobyte(@env21), .hibyte(@env21), $90, $12, $a1, $72, $4b, .lobyte(@env11), .hibyte(@env11), $14
	.byte $a1, $73, $4d, $20, $a1, $74, $4b, .lobyte(@env3), .hibyte(@env3), $28, $a1, $75, $4b, .lobyte(@env5), .hibyte(@env5)
	.byte $2c, $95, $76, $4d, $2d, $95, $75, $97, $74, $4b, .lobyte(@env19), .hibyte(@env19), $2c, $95, $73, $95, $4f, $01, $81
	.byte $7f, $4b, .lobyte(@env16), .hibyte(@env16), $4c, $8a, $28, $89, $25, $89, $27, $89, $28, $89, $2a, $89, $2c, $89, $2d
	.byte $89, $31, $89, $33, $95, $49, .lobyte(@env24), .hibyte(@env24), $af, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a
	.byte $2f, $89, $2a, $89, $2c, $95, $49, .lobyte(@env24), .hibyte(@env24), $c5, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $81, $79
	.byte $41, $16
	.word @song0ref1289
	.byte $41, $1c
	.word @song0ref79
	.byte $4f, $00, $97, $71, $4b, .lobyte(@env21), .hibyte(@env21), $90, $19, $a1, $72, $4b, .lobyte(@env5), .hibyte(@env5)
	.byte $19, $a1, $73, $4b, .lobyte(@env11), .hibyte(@env11), $20, $a1, $74, $4b, .lobyte(@env3), .hibyte(@env3), $28, $9b
	.byte $72, $85, $75, $4b, .lobyte(@env21), .hibyte(@env21), $2c, $95, $76, $4b, .lobyte(@env5), .hibyte(@env5), $2c, $95
	.byte $75, $97, $74, $4d, $28, $95, $73, $97, $72, $4b, .lobyte(@env3), .hibyte(@env3), $23, $ad, $71, $4b, .lobyte(@env5)
	.byte .hibyte(@env5), $1c, $a9, $4f, $01, $81, $4b, .lobyte(@env16), .hibyte(@env16), $4c, $43, $1c, $7f, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $8a, $31, $95, $49, .lobyte(@env24), .hibyte(@env24), $a3, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $8a, $2e, $89, $2a, $89, $25, $89, $22, $95, $49, .lobyte(@env24), .hibyte(@env24), $a3, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $8a, $1e, $89, $19, $89, $16, $89, $18, $95, $49, .lobyte(@env24), .hibyte(@env24), $c7, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $8a, $14, $95, $49, .lobyte(@env24), .hibyte(@env24), $c7, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a, $14
	.byte $95, $49, .lobyte(@env24), .hibyte(@env24), $af, $79, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88
	.byte $41, $52
	.word @song0ref25
	.byte $4f, $00, $14, $83, $17, $89, $00, $83, $14, $00, $87, $14, $00, $87, $14, $83, $17, $89, $00, $83, $14, $00, $87, $14
	.byte $83, $00, $83, $14, $83, $17, $89, $00, $83, $14, $00, $87, $14, $00, $87, $17, $83, $00, $83, $14, $00, $87, $14
	.byte $41, $12
	.word @song0ref26
	.byte $41, $25
	.word @song0ref70
	.byte $41, $15
	.word @song0ref7
	.byte $19, $00, $87
	.byte $41, $10
	.word @song0ref32
	.byte $14, $00, $87
@song0ref1750:
	.byte $14, $00, $87, $14, $00, $87, $15, $83, $17, $89, $00, $83, $17, $00, $87, $17, $83, $00, $83, $1e, $83, $00, $83, $17
	.byte $00, $87, $17, $83, $00, $83
	.byte $41, $16
	.word @song0ref79
	.byte $41, $10
	.word @song0ref1750
	.byte $00, $87, $15, $83, $17, $89, $00, $83, $17, $00, $87, $17, $00, $87, $15, $83, $17, $89, $00, $83, $17, $00, $87, $17
	.byte $00, $87, $17, $83, $00, $83, $14, $00, $87, $14, $00, $87, $14, $00, $87, $20, $dd, $20, $95, $45, $89, $22, $95, $45
	.byte $89, $24, $89, $45, $89, $7a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $20, $95, $49, .lobyte(@env24), .hibyte(@env24)
	.byte $97, $78, $af, $7a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $1c, $95, $49, .lobyte(@env24), .hibyte(@env24)
	.byte $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $20, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $88, $1e, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $78, $af, $76, $af, $7a, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $88, $19, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $78, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $88, $1b, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $76, $af, $74, $af, $78, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $88, $19, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $1b
	.byte $95, $76, $49, .lobyte(@env24), .hibyte(@env24), $97, $74, $97, $72, $97, $78, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $88, $1c, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $1e
	.byte $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $7a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $20, $95, $49
	.byte .lobyte(@env24), .hibyte(@env24), $97, $78, $97, $7a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $14, $89, $1c
	.byte $89, $20, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $78, $97, $7a, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $88, $1e, $89, $20, $89, $22, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $78, $97, $7a, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $88, $16, $89, $1e, $89, $22, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $78, $97, $7a, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $88, $20, $89, $22, $89, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8e, $23, $95, $49, .lobyte(@env24)
	.byte .hibyte(@env24), $97, $78, $97, $7a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8e, $16, $89, $17, $89, $20, $ad, $78
	.byte $ff, $8f, $7a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $1e, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $78
	.byte $af, $7a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88, $20, $95, $49, .lobyte(@env24), .hibyte(@env24), $97, $78
	.byte $af, $76, $af, $74, $af, $49, .lobyte(@env0), .hibyte(@env0), $4a, $00, $ad, $73, $4f, $02, $8c, $38
	.byte $41, $17
	.word @song0ref1128
	.byte $42
	.word @song0ch1loop
@song0ch2:
	.byte $8c, $19, $ff, $ff, $fd, $ff, $bf, $40, $4e
@song0ref2132:
	.byte $83, $3f, $83, $3d, $83, $38, $83, $36, $83, $31, $83, $2a, $83, $27, $83, $25, $83, $20, $83, $1b, $89, $00, $89, $92
	.byte $2c, $83, $2c, $83, $2c, $89, $25, $83, $00, $83, $25, $83, $00, $83, $2c, $89, $2c, $89, $2c, $89, $2c, $89, $2c, $89
@song0ch2loop:
@song0ref2181:
	.byte $25, $83, $00, $8f, $25, $83, $00, $8f, $2c, $89, $00, $a1, $25, $83, $00, $9b, $25, $83, $00, $83, $2c, $89, $00, $89
	.byte $25, $83, $00, $a7, $25, $83, $00, $8f, $2c, $89, $00, $a1
@song0ref2217:
	.byte $25, $83, $00, $83, $25, $83, $00, $83, $25, $83, $00, $8f, $2c, $89, $00, $89, $25, $83, $00, $8f
	.byte $41, $23
	.word @song0ref2181
	.byte $89, $25, $83, $00, $8f
	.byte $41, $14
	.word @song0ref2217
	.byte $41, $38
	.word @song0ref2181
	.byte $41, $23
	.word @song0ref2181
	.byte $89, $25, $83, $00, $8f
	.byte $41, $14
	.word @song0ref2217
@song0ref2262:
	.byte $25, $83, $00, $a7, $2c, $89, $00, $a1, $25, $83, $00, $9b, $25, $83, $00, $83, $2c, $89, $00, $b9, $25, $83, $00, $8f
	.byte $2c, $89, $00, $a1, $25, $83, $00, $a7, $2c, $89, $00, $a1
	.byte $41, $22
	.word @song0ref2262
	.byte $33, $89, $2e, $89, $2c, $89
	.byte $41, $24
	.word @song0ref2262
	.byte $41, $1b
	.word @song0ref2181
	.byte $8f, $25, $83, $00, $83, $25, $83, $00, $9b, $2c, $89, $00, $95, $2c, $89, $00, $95, $34, $89, $34, $89, $31, $89, $31
	.byte $89, $2f, $89, $2f, $89
	.byte $41, $38
	.word @song0ref2181
	.byte $41, $23
	.word @song0ref2181
	.byte $89, $25, $83, $00, $8f
	.byte $41, $14
	.word @song0ref2217
	.byte $41, $38
	.word @song0ref2181
	.byte $41, $23
	.word @song0ref2181
	.byte $89, $25, $83, $00, $8f
	.byte $41, $14
	.word @song0ref2217
	.byte $41, $24
	.word @song0ref2262
	.byte $41, $22
	.word @song0ref2262
	.byte $33, $89, $2e, $89, $2c, $89
	.byte $41, $24
	.word @song0ref2262
	.byte $41, $22
	.word @song0ref2262
	.byte $33, $89, $2e, $89, $2c, $89
@song0ref2394:
	.byte $25, $83, $00, $cb, $25, $83, $00, $8f, $25, $83, $00, $83, $25, $83, $00, $8f, $2c, $89, $00, $a1, $25, $83, $00, $bf
	.byte $25, $83, $00, $83
@song0ref2422:
	.byte $25, $83, $00, $8f, $25, $83, $00, $83, $25, $83, $00, $8f, $2c, $89, $25, $83, $00, $9b
	.byte $41, $2e
	.word @song0ref2394
	.byte $41, $12
	.word @song0ref2394
	.byte $25, $83, $00, $9b
	.byte $41, $12
	.word @song0ref2394
	.byte $25, $83, $00, $9b, $25, $83, $00, $a7, $2c, $89, $00, $95
	.byte $41, $12
	.word @song0ref2422
	.byte $25, $83, $00, $ff, $b7
	.byte $41, $23
	.word @song0ref2181
	.byte $89, $25, $83, $00, $8f, $25, $83, $00, $83, $25, $83, $00, $83, $25, $95, $2c, $89, $00, $89, $25, $89, $00, $89
	.byte $41, $38
	.word @song0ref2181
	.byte $41, $38
	.word @song0ref2181
	.byte $41, $38
	.word @song0ref2181
	.byte $25, $83, $00, $8f, $25, $83, $00, $8f, $2c, $89, $00, $ff, $81, $8c, $40, $50
	.byte $41, $16
	.word @song0ref2132
	.byte $95, $92, $2c, $89, $2c, $89, $00, $89, $2c, $89, $00, $89, $2c, $89, $00, $89, $2c, $89, $42
	.word @song0ch2loop
@song0ch3:
	.byte $80
@song0ref2549:
	.byte $20, $95, $23, $95, $20, $95, $23, $95, $20, $95, $23, $95, $20, $95, $23, $95
	.byte $41, $10
	.word @song0ref2549
	.byte $41, $10
	.word @song0ref2549
	.byte $84, $14, $95, $80, $23, $95, $20, $95, $23, $89, $84, $14, $83, $14, $83, $14, $89, $82, $14, $89, $14, $89, $84, $14
	.byte $89, $14, $89, $14, $89, $14, $89, $14, $89
@song0ch3loop:
@song0ref2605:
	.byte $86, $1f, $95, $82, $14, $95, $84, $14, $89, $80, $20, $89, $20, $89, $20, $89, $82, $14, $95, $80, $20, $89, $82, $14
	.byte $89, $84, $14, $89, $80, $22, $89, $82, $14, $89, $80, $20, $89, $20
@song0ref2643:
	.byte $95, $82, $14, $95, $84, $14, $89, $80, $20, $89, $20, $89
@song0ref2655:
	.byte $20, $89, $82, $14, $89, $14, $89, $14, $89, $80, $20, $89, $84, $14, $95, $82, $14, $89, $80, $20, $89, $82, $14, $95
	.byte $14, $95, $84, $14, $89, $80, $20, $89, $20, $89, $20, $89, $82, $14, $89, $80, $20, $89, $20, $89, $82, $14, $89, $84
	.byte $14, $95, $82, $14, $89, $80, $20, $89, $20, $95, $82, $14, $95, $84, $14, $89, $80, $20, $89, $82, $14, $89, $80
@song0ref2726:
	.byte $20, $89, $82, $14, $89, $14, $83, $80, $20, $83, $82, $14, $89, $80, $20, $89, $84, $14, $95, $82, $14, $89, $80, $20
	.byte $89
	.byte $41, $65
	.word @song0ref2605
@song0ref2754:
	.byte $89, $80, $20, $89, $82, $14, $89, $80, $20
@song0ref2763:
	.byte $89, $86, $1f, $ad
@song0ref2767:
	.byte $84, $14, $95, $80, $20, $89, $20, $89
@song0ref2775:
	.byte $82, $14, $95, $80, $20, $89, $82, $14, $89, $84, $14, $95, $80, $20, $89, $20, $89, $20, $95, $82
@song0ref2795:
	.byte $14, $89, $80, $20, $89, $84, $14, $95, $80, $20, $89, $20, $89, $82, $14, $95, $80, $20, $89, $20, $89
	.byte $41, $12
	.word @song0ref2767
	.byte $41, $1e
	.word @song0ref2775
	.byte $84, $14, $89, $82, $22, $89, $22, $89, $22
	.byte $41, $27
	.word @song0ref2763
	.byte $84, $14, $95, $80, $20, $89, $20, $89, $82, $14, $95, $14, $95, $84, $14, $89, $80, $20, $89, $20, $95, $82, $14, $89
	.byte $80, $20, $95, $82, $14, $89, $84, $14, $95, $82, $14, $89, $80, $20, $89, $82, $14, $89, $14, $89, $80, $20, $95, $84
	.byte $14, $89, $80, $20, $89, $20, $89, $84, $14, $89, $80, $20, $95, $82, $22, $89, $22, $89, $22, $89, $22, $89, $22, $89
	.byte $22, $89
	.byte $41, $6a
	.word @song0ref2605
	.byte $41, $65
	.word @song0ref2605
	.byte $41, $2d
	.word @song0ref2754
	.byte $41, $12
	.word @song0ref2767
	.byte $41, $1e
	.word @song0ref2775
	.byte $84, $14, $89, $82, $22, $89, $22, $89, $22
	.byte $41, $27
	.word @song0ref2763
	.byte $41, $12
	.word @song0ref2767
	.byte $41, $1e
	.word @song0ref2775
	.byte $84, $14, $89, $82, $22, $89, $22, $89, $22, $89, $86, $1f, $ad, $7f, $84, $14, $95, $80, $20, $89, $82, $14, $89, $80
	.byte $20, $89, $82, $14, $89
	.byte $41, $10
	.word @song0ref2795
@song0ref2973:
	.byte $84, $14, $95, $82, $14, $89, $14, $89, $80, $20, $89, $82, $14, $89
@song0ref2987:
	.byte $14, $89, $80, $20, $89, $84, $14, $89, $82, $14, $89, $80, $20, $89, $20, $89, $82, $14, $95, $80, $20, $89, $20, $89
	.byte $84, $14, $95, $80, $20, $89, $82, $14, $89, $80, $20, $89, $82, $14, $89
	.byte $41, $10
	.word @song0ref2795
	.byte $41, $26
	.word @song0ref2973
	.byte $41, $1c
	.word @song0ref2987
	.byte $41, $1c
	.word @song0ref2987
	.byte $14, $89, $80, $20, $89, $84, $14, $89, $82, $14, $89, $80, $20, $89, $20, $89, $82, $14, $dd, $84, $14, $a1, $14, $a1
	.byte $14, $95
	.byte $41, $22
	.word @song0ref2605
	.byte $82, $14, $89, $80
	.byte $41, $32
	.word @song0ref2655
	.byte $20, $89
	.byte $41, $12
	.word @song0ref2726
	.byte $41, $1a
	.word @song0ref2605
	.byte $86, $1f
	.byte $41, $10
	.word @song0ref2643
	.byte $95, $84, $14, $89, $80, $22, $89, $82, $14, $89, $80, $20, $89
	.byte $41, $25
	.word @song0ref2605
	.byte $83, $20, $83, $82, $14, $89, $14, $89, $14, $89, $80, $20, $89, $84, $14, $89, $80, $20, $89, $82, $14, $89, $80, $20
	.byte $89, $86, $1f, $95, $82, $14, $95, $84, $14, $95, $80, $20, $89, $20, $89, $82, $14, $89, $14, $89, $80, $20, $89, $82
	.byte $14, $89, $84, $14, $89, $14, $89, $82, $14, $89, $80, $20, $89, $84, $14, $89, $82, $14, $95, $14, $95, $14, $95, $14
	.byte $83, $80, $20, $83, $84, $14, $89, $14, $95, $14, $95, $14, $95, $14, $89, $42
	.word @song0ch3loop
@song0ch4:
	.byte $52, $80, $ff, $ff, $ff, $ff, $bf, $17, $dd, $0d, $89, $04, $95, $05, $95, $0c, $95, $11, $89
@song0ch4loop:
@song0ref3213:
	.byte $06, $95, $08, $95, $06, $95, $08, $89, $08, $89, $06, $89, $07, $89, $01, $89, $08, $89, $08, $89, $01, $95, $08, $89
	.byte $0c, $95, $01, $95, $0c, $95, $01, $89, $01, $89, $0c, $89, $0d, $89, $07, $89, $01, $89, $01, $89, $0e, $95, $01, $89
	.byte $0b, $95, $0e, $95, $0b, $95, $0e, $89, $0e, $89, $0b, $89, $0d, $89, $07, $89, $0e, $89, $0e, $89, $07, $95, $0e, $89
	.byte $04, $95, $0d, $95, $04, $95, $0d, $89, $0d, $89, $05, $89, $05, $89, $07, $95, $07, $89, $01, $89, $15, $89, $02, $89
	.byte $41, $60
	.word @song0ref3213
@song0ref3312:
	.byte $04, $95, $0d, $95, $04, $95, $0d, $89, $0d, $89, $04, $95, $0d, $95, $04, $95, $0d, $89, $0d, $89
	.byte $41, $14
	.word @song0ref3312
@song0ref3335:
	.byte $09, $95, $02, $95, $09, $95, $02, $89, $02, $89, $09, $95, $02, $95, $09, $95, $02, $89, $02, $89, $0b, $95, $0e, $95
	.byte $0b, $95, $0e, $89, $0e, $89, $05, $95, $07, $95, $05, $95, $07, $89, $07, $89, $0b, $95, $0e, $95, $0b, $95, $0e, $89
	.byte $0e, $89, $0b, $95, $0e, $95, $0b, $95, $0e, $89, $0e, $89
	.byte $41, $14
	.word @song0ref3335
	.byte $41, $14
	.word @song0ref3312
@song0ref3401:
	.byte $05, $95, $07, $95, $05, $95, $07, $89, $07, $89, $05, $89, $07, $89, $05, $89, $12, $89, $0d, $89, $07, $89, $0c, $89
	.byte $01, $89
	.byte $41, $60
	.word @song0ref3213
	.byte $41, $60
	.word @song0ref3213
	.byte $41, $14
	.word @song0ref3312
	.byte $41, $14
	.word @song0ref3312
	.byte $41, $3c
	.word @song0ref3335
	.byte $41, $14
	.word @song0ref3335
	.byte $41, $14
	.word @song0ref3312
	.byte $41, $1a
	.word @song0ref3401
	.byte $0b, $ad, $17, $95, $0b, $89, $0b, $95, $0b, $89, $0b, $ad, $0b, $95, $0b, $ad, $17, $95, $0b, $89, $0b, $95, $0b, $89
	.byte $0b, $ad, $0b, $95, $05, $ad, $17, $95, $05, $89, $05, $95, $05, $89, $05, $ad, $05, $95, $06, $ad, $17, $95, $06, $89
	.byte $06, $95, $06, $95, $06, $89, $06, $95, $05, $95, $04, $ad, $17, $95, $04, $89, $04, $95, $04, $89, $04, $ad, $04, $95
	.byte $0c, $ad, $17, $95, $0c, $89, $0c, $95, $0c, $95, $0c, $89, $0c, $95, $0b, $95, $05, $ad, $17, $95, $05, $89, $05, $95
	.byte $05, $89, $05, $ad, $04, $95, $05, $c5, $07, $95, $17, $a1, $17, $a1, $17, $95
@song0ref3563:
	.byte $09, $89, $09, $89, $02, $95, $05, $89, $05, $89, $07, $95, $0c, $89, $0c, $89, $01, $95, $02, $89, $02, $89, $09, $89
	.byte $09, $89, $04, $89, $04, $89, $0d, $95, $10, $89, $10, $89, $14, $95, $06, $89, $06, $89, $08, $95, $14, $89, $14, $89
	.byte $10, $89, $10, $89, $0f, $89, $0f, $89, $12, $95, $0a, $89, $0a, $89, $13, $95, $10, $89, $10, $89, $14, $95, $13, $89
	.byte $13, $89, $0a, $89, $0a, $89, $05, $89, $05, $89, $07, $95, $0c, $89, $0c, $89, $01, $95, $12, $89, $12, $89, $15, $95
	.byte $07, $89, $07, $89, $05, $89, $05, $89
	.byte $41, $1a
	.word @song0ref3563
	.byte $0f, $89, $0f, $89, $12, $95, $04, $89, $04, $89, $0d, $95, $10, $89, $10, $89, $14, $95, $0d, $89, $0d, $89, $0f, $89
	.byte $0f
@song0ref3695:
	.byte $89, $03, $89, $03, $89, $06, $95, $09, $89, $09, $89, $02, $95, $05, $89, $05, $89, $07, $95, $02, $89, $02, $89, $09
	.byte $89, $09
	.byte $41, $1a
	.word @song0ref3695
	.byte $89, $07, $dd, $16, $89, $16, $95, $16, $89, $17, $89, $17, $89, $16, $95, $17, $89, $16, $95, $16, $95, $16, $95, $16
	.byte $89, $0d, $89, $04, $95, $05, $95, $0c, $95, $11, $89, $42
	.word @song0ch4loop
